package com.fynnjason.sanews.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fynnjason.sanews.bean.SearchRecordBean;

import com.fynnjason.sanews.greendao.SearchRecordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchRecordBeanDaoConfig;

    private final SearchRecordBeanDao searchRecordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchRecordBeanDaoConfig = daoConfigMap.get(SearchRecordBeanDao.class).clone();
        searchRecordBeanDaoConfig.initIdentityScope(type);

        searchRecordBeanDao = new SearchRecordBeanDao(searchRecordBeanDaoConfig, this);

        registerDao(SearchRecordBean.class, searchRecordBeanDao);
    }
    
    public void clear() {
        searchRecordBeanDaoConfig.clearIdentityScope();
    }

    public SearchRecordBeanDao getSearchRecordBeanDao() {
        return searchRecordBeanDao;
    }

}
